#!/bin/bash

set -euo pipefail

index=${1:-}
history_file="${XDG_STATE_HOME:-$HOME/.local/state}/omarchy/clipboard-history.json"

[[ $index =~ ^[0-9]+$ ]] || exit 2
[[ -r $history_file ]] || exit 1

entry_type=$(jq -er --argjson index "$index" '.[$index].type' "$history_file")

case "$entry_type" in
  text)
    jq -er --argjson index "$index" '.[$index].text | type == "string"' "$history_file" >/dev/null
    jq -jr --argjson index "$index" '.[$index].text' "$history_file" | wl-copy
    ;;
  image)
    mime=$(jq -er --argjson index "$index" '.[$index].mime // "image/png"' "$history_file")
    path=$(jq -er --argjson index "$index" '.[$index].path' "$history_file")
    [[ -r $path ]] || exit 1
    wl-copy --type "$mime" < "$path"
    ;;
  *) exit 2 ;;
esac
